---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя.
implicit:
  - Сайт должен корректно открываться на Lenovo Tab 3
  - В каталоге присутствует более 45 позиций
